removed pcd_load from line.fit() which caused error
"pcd_load" variable was in place of "thresh" argument of the .fit function call leading to following error
Traceback (most recent call last):
    A, B, inliers = line.fit(points,pcd_load, thresh=15)
TypeError: Line.fit() got multiple values for argument 'thresh'